permissions:
  default:
    _type: default-block
    allow:
      - core
      - coding
      - knowledge-work
      - knowledge-code
      - devops
      - diagrams
  consumers:
    claude-code:
      _type: default-block
      consumerGroupKey: claude-code
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-code
        - devops
        - diagrams
    claude-desktop:
      _type: default-block
      consumerGroupKey: claude-desktop
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-code
        - devops
        - diagrams
    vscode-copilot:
      _type: default-block
      consumerGroupKey: vscode-copilot
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-code
        - devops
        - diagrams
    vscode-insiders-copilot:
      _type: default-block
      consumerGroupKey: vscode-insiders-copilot
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-code
        - devops
        - diagrams
    opencode:
      _type: default-block
      consumerGroupKey: opencode
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-code
        - devops
        - diagrams
    cline:
      _type: default-block
      consumerGroupKey: cline
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-code
        - devops
        - diagrams
    cline-standalone:
      _type: default-block
      consumerGroupKey: cline-standalone
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-code
        - devops
        - diagrams
    kilocode:
      _type: default-block
      consumerGroupKey: kilocode
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-code
        - devops
        - diagrams
    goose:
      _type: default-block
      consumerGroupKey: goose
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-code
        - devops
        - diagrams
toolGroups:
  - name: core
    services:
      sequential-thinking: "*"
      memory: "*"
  - name: coding
    services:
      context7: "*"
  - name: knowledge-work
    services:
      qdrant-work: "*"
  - name: knowledge-code
    services:
      qdrant-code: "*"
  - name: devops
    services:
      azure-devops: "*"
  - name: diagrams
    services:
      mermaid: "*"
auth:
  enabled: false
toolExtensions:
  services: {}
targetServerAttributes:
  context7:
    inactive: false
  sequential-thinking:
    inactive: false
  memory:
    inactive: false
  azure-devops:
    inactive: false
