permissions:
  default:
    _type: default-block
    allow: []
  consumers:
    Claude Desktop:
      _type: default-block
      consumerGroupKey: claude-ai (via mcp-remote 0.1.30) Profile
      allow:
        - core
        - browser
    VSCode:
      _type: default-block
      consumerGroupKey: Visual Studio Code (via mcp-remote 0.1.31) Profile
      allow:
        - core
        - browser
    OpenCode:
      _type: default-block
      consumerGroupKey: opencode Profile
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-personal
        - knowledge-code
        - browser
    Copilot:
      _type: default-block
      consumerGroupKey: vscode-copilot Profile
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-personal
        - knowledge-code
        - browser
    Copilot Insiders:
      _type: default-block
      consumerGroupKey: vscode-insiders-copilot Profile
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-personal
        - knowledge-code
    Cline:
      _type: default-block
      consumerGroupKey: cline Profile
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-personal
        - knowledge-code
        - browser
    Kilocode:
      _type: default-block
      consumerGroupKey: kilocode Profile
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-personal
        - knowledge-code
        - browser
    Goose:
      _type: default-block
      consumerGroupKey: goose Profile
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-personal
        - knowledge-code
        - browser
    vscode-copilot:
      _type: default-block
      consumerGroupKey: Visual Studio Code - Insiders (via mcp-remote 0.1.37) Profile
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-personal
        - knowledge-code
    vscode-insiders-copilot:
      _type: default-block
      consumerGroupKey: Visual Studio Code - Insiders (via mcp-remote 0.1.37) Profile
      allow:
        - core
        - coding
        - knowledge-work
        - knowledge-personal
        - knowledge-code
toolGroups:
  - name: core
    services:
      sequential-thinking: "*"
      memory: "*"
  - name: coding
    services:
      context7: "*"
  - name: knowledge-work
    services:
      qdrant-work: "*"
  - name: knowledge-personal
    services:
      qdrant-personal: "*"
  - name: knowledge-code
    services:
      qdrant-code: "*"
  - name: browser
    services:
      kapture: "*"
      playwright: "*"
      browser-use: "*"
  - name: home
    services:
      hass-mcp: "*"
  - name: creative
    services:
      photoshop: "*"
auth:
  enabled: false
toolExtensions:
  services: {}
targetServerAttributes:
  context7:
    inactive: false
