permissions:
  default:
    _type: default-block
    allow: []
  consumers:
    Claude Desktop:
      _type: default-block
      consumerGroupKey: claude-ai (via mcp-remote 0.1.30) Profile
      allow:
      - core
      - browser
    VSCode:
      _type: default-block
      consumerGroupKey: Visual Studio Code (via mcp-remote 0.1.31) Profile
      allow:
      - core
      - browser
    OpenCode:
      _type: default-block
      consumerGroupKey: opencode Profile
      allow:
      - core
      - coding
      - browser
    Copilot:
      _type: default-block
      consumerGroupKey: vscode-copilot Profile
      allow:
      - core
      - coding
      - browser
    Cline:
      _type: default-block
      consumerGroupKey: cline Profile
      allow:
      - core
      - coding
      - browser
    Kilocode:
      _type: default-block
      consumerGroupKey: kilocode Profile
      allow:
      - core
      - coding
      - browser
    Goose:
      _type: default-block
      consumerGroupKey: goose Profile
      allow:
      - core
      - coding
      - browser
toolGroups:
- name: core
  services:
    sequential-thinking: '*'
    memory: '*'
- name: coding
  services:
    context7: '*'
- name: browser
  services:
    kapture: '*'
    playwright: '*'
    browser-use: '*'
- name: home
  services:
    hass-mcp: '*'
- name: creative
  services:
    photoshop: '*'
auth:
  enabled: false
toolExtensions:
  services: {}
targetServerAttributes:
  context7:
    inactive: false
